apiVersion: v1
kind: Service
metadata:
  name: app-receiver-service
  labels:
    {{- include "appworkshop.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.workshop.io/name: appreceiver
