name: Integration workflow

concurrency:
  group: ci-${{ github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

env:
  GO_VERSION: 1.24.2
  REGISTRY: ghcr.io

permissions:
  contents: write
  packages: write
  pull-requests: write

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workdir: [./app_sender, ./app_receiver]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        working-directory: ${{ matrix.workdir }}
        run: go test ./...

  lint:
    name: Run linters
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        workdir: [./app_sender, ./app_receiver]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Go environment
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Run tests
        working-directory: ${{ matrix.workdir }}
        run: go vet

  build:
    needs: [lint, test]
    name: Build container image
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        name: [app_sender, app_receiver]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY }}/jan-re/${{ matrix.name }}
          tags: |
            type=raw,value=0.0.1

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.15.0
        with:
          context: .
          file: ./${{ matrix.name }}/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  chart:
    needs: [build]
    name: Build Helm chart
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Package and push
        working-directory: ./helm
        run: |
          helm package . --version 0.0.1 --app-version 0.0.1
          helm push appworkshop-0.0.1.tgz oci://ghcr.io/jan-re/charts
